#!/bin/sh
BACKUP_DIR=/home/root/openhr20_backup

if [ ! -d $BACKUP_DIR ]; then
	mkdir $BACKUP_DIR
fi

if [ -d /tmp/openhr20 ]; then
	cp -a /tmp/openhr20/*.rrd $BACKUP_DIR
fi

if [ -f /tmp/openhr20.sqlite ]; then
	cp /tmp/openhr20.sqlite $BACKUP_DIR
fi
